### 查看工作目录 Check working directory

In [4]:
import os
print(os.getcwd())
# os.chdir('') 变更工作目录

/Users/baobo/Desktop/Github/2_Statistical_Methods_on_Complex_Data_with_R_and_Python/chp13_R_Python


### 批量查看文件 Check File

In [5]:
import os 
from os.path import join
for (dirname,dirs, files) in os.walk('/Users/baobo/Desktop/Github/2_Statistical_Methods_on_Complex_Data_with_R_and_Python/chp13_R_Python'):
    for filename in files:
        if filename.endswith('.txt'):
            thefile = os.path.join(dirname, filename)
            print(thefile, os.path.getsize(thefile))

/Users/baobo/Desktop/Github/2_Statistical_Methods_on_Complex_Data_with_R_and_Python/chp13_R_Python/test.txt 4026


### 数据处理基本模块导入 data processing modules

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

### 向量、矩阵、列表的索引 index of vectors, matrices, and lists

In [7]:
y = [[1, 2], [1, 2, 3], ['ss', 'swa', 'stick']]
y[2], y[2][:2], y[1][1:]

(['ss', 'swa', 'stick'], ['ss', 'swa'], [2, 3])

In [8]:
x = 'A poet can survive everything but a misprint.'
x[:10] + x[10:20] + x[20:30] + x[30:40] + x[40:]

'A poet can survive everything but a misprint.'

### 列表中添加删除元素 append and delete elements in list

In [14]:
x = [[1, 2], [3, 5, 7], 'Oscar Wilde']
y = ['save', 'the world']
x.append(y); print(x)
x.extend(y); print(x)

x.pop(); print(x)
x.pop(2); print(x)
x.remove('save'); print(x)
del x[0]; print(x, type(x))

[[1, 2], [3, 5, 7], 'Oscar Wilde', ['save', 'the world']]
[[1, 2], [3, 5, 7], 'Oscar Wilde', ['save', 'the world'], 'save', 'the world']
[[1, 2], [3, 5, 7], 'Oscar Wilde', ['save', 'the world'], 'save']
[[1, 2], [3, 5, 7], ['save', 'the world'], 'save']
[[1, 2], [3, 5, 7], ['save', 'the world']]
[[3, 5, 7], ['save', 'the world']] <class 'list'>


### 元组 tuple

In [15]:
x = (0, 12, 345, 67, 8, 9, 'we', 'they')
print(x, x[-4:-1])

(0, 12, 345, 67, 8, 9, 'we', 'they') (8, 9, 'we')


### 范围 range, xrange

In [18]:
x = range(2, 11, 2)
print('x = {}, list(x) = {}'.format(x, list(x)))
print('type of x is {}'.format(type(x)))

x = range(2, 11, 2), list(x) = [2, 4, 6, 8, 10]
type of x is <class 'range'>


### 字典格式 dictionary

In [19]:
data = {'age': 34, 'Children': [1,2], 1: 'apple', 'zip': 'NA'}
print(type(data))
print('age = ', data['age'])
data['age'] = 99
data['name'] = 'abc'
print(data)

<class 'dict'>
age =  34
{'age': 99, 'Children': [1, 2], 1: 'apple', 'zip': 'NA', 'name': 'abc'}


### 集合运算 set operations

In [2]:
x = set(['we', 'you', 'he', 'I', 'they']); y = set(['I', 'we', 'us'])
x.add('all'); print(x, type(x), len(x))
set.add(x, 'none'); print(x)
print('set.difference(x,y) = ', set.difference(x,y))
print('set.union(x,y) = ', set.union(x,y))
print('set.intersection(x,y) = ', set.intersection(x,y))
x.remove('none')
print('x = ', x, '\n', 'y = ', y)

{'they', 'he', 'we', 'you', 'all', 'I'} <class 'set'> 6
{'they', 'he', 'we', 'none', 'you', 'all', 'I'}
set.difference(x,y) =  {'they', 'he', 'none', 'you', 'all'}
set.union(x,y) =  {'they', 'he', 'we', 'none', 'us', 'all', 'you', 'I'}
set.intersection(x,y) =  {'I', 'we'}
x =  {'they', 'he', 'we', 'you', 'all', 'I'} 
 y =  {'us', 'I', 'we'}


### 使用id来确定函数储存位置  

In [5]:
x = 1; y = x; print(x, y, id(x), id(y))
x = 2.0; print(x, y, id(x), id(y))
x = [1, 2, 3]; y = x; y[0] = 10
print(x, y, id(y))
x = [1, 2, 3]; y = x[:]
print(x, y, id(x) == id(y), id(x[0]) == id(y[0]))
print(id(x[1]) == id(y[1]), id(x[2]) == id(y[2]))

1 1 4511178072 4511178072
2.0 1 4570557648 4511178072
[10, 2, 3] [10, 2, 3] 4646085760
[1, 2, 3] [1, 2, 3] False True
True True


### 定义函数 包括lambda函数 define function and lambda function

In [2]:
def f(x): return x**2-x
g = lambda x: max(x**2, x**3)
print(g(2))
print(list(map(lambda x : x**2+1-abs(x), [1.2, 5.7, 23.6, 6])))

8
[1.24, 27.790000000000003, 534.36, 31]


In [3]:
from random import *
def RandomHappy():
    if randint(1, 100) > 50:
        x = 'Happy'
    else:
        x = 'Unhappy'
    if randint(1, 100) > 50:
        y = 'Happy'
    else:
        y = 'Unhappy'
    if x == 'Happy' and y == 'Happy':
        print('You both are happy!')
    elif x != y:
        print('One of you is happy!')
    else:
        print('You are miserable TAT')

RandomHappy()

One of you is happy!


### for循环和打开txt文件 For loop in python and open txt file

In [9]:
# with open ('test.txt', 'r') as f:
#     lines = f.readlines()
# lines[1:20]

################################################################################

x = 'Just a word'

for i in x:
    print(i)

for i in x.split():
    print(i, len(i))

print('\n------------------------------------------------------------------------------\n')

for i in [-1, 4, 2, 27, -34]:
    if i > 0 and i < 15:
        print(i, i**2 + i/ .5)
    elif i <0 and abs(i) > 5:
        print(abs(i))
    else:
        print(4.5 ** i)

J
u
s
t
 
a
 
w
o
r
d
Just 4
a 1
word 4

------------------------------------------------------------------------------

0.2222222222222222
4 24.0
2 8.0
4.3324930223107386e+17
34


In [12]:
x = range(5)
x 
y = []
for i in range(len(x)):
    if float(i/2) == i/2:
        y.append(x[i] ** 2)
print('y = ', y)

z = [x[i] ** 2 for i in range(len(x)) if float(i/2) == i/2]

print('z = ', z)

print('##################################################################################')

my_list = ['mouse', [1,2,3], ['a']]
my_list_copy = []
my_list_mix = []
for i in my_list:
    my_list_copy.append(i)
    my_list_mix.extend(i)
print(my_list_copy, '\n', my_list_mix)

y =  [0, 1, 4, 9, 16]
z =  [0, 1, 4, 9, 16]
##################################################################################
['mouse', [1, 2, 3], ['a']] 
 ['m', 'o', 'u', 's', 'e', 1, 2, 3, 'a']


### Numpy 模块

In [ ]:
import numpy as np
x = np.random.randn(25, 5)
# np.savetxt('tabs.txt', x) # 保存为指标分隔符的文件
# np.savetxt('commas.csv', delimiter = ',') # 保存为逗号分隔符的文件
# u = np.loadtxt('commas.csv', delimiter = ',') # 读取逗号分隔符的文件
# v = np.loadtxt('tabs.txt') # 读取制表符分隔文件

In [16]:
### 矩阵和数组
import numpy as np
y = np.array([[[1, 4, 7], [2, 5, 8]], [[3, 6, 9], [10, 100, 1000]]])
print(y)

print(np.shape(y))

print(type(y), y.dtype)

print(y[1, 0, 0], y[0, 1, :])

[[[   1    4    7]
  [   2    5    8]]

 [[   3    6    9]
  [  10  100 1000]]]
(2, 2, 3)
<class 'numpy.ndarray'> int64
3 [2 5 8]


In [19]:
import numpy as np
u = np.array([0, 1, 2]); v = np.array([5, 2, 7])
print(u.shape, v.shape)
print(u + v, u/v, np.dot(u, v))

u = [0.0, 1, 2]; v = [5, 2, 7]
u = np.array(u); v = np.array(v)
print(u + v)
print(u/v)
print(v/3, v/3., v/float(3), (v - 2.5) ** 2)

(3,) (3,)
[5 3 9] [0.         0.5        0.28571429] 16
[5. 3. 9.]
[0.         0.5        0.28571429]
[1.66666667 0.66666667 2.33333333] [1.66666667 0.66666667 2.33333333] [1.66666667 0.66666667 2.33333333] [ 6.25  0.25 20.25]
